#!/usr/bin/env npx ts-node
// package/adapters/command-code/generate-agents-md.ts
// Generates a Command Code-compatible AGENTS.md with SP0 enrichment context embedded.
//
// Usage:
//   npx ts-node generate-agents-md.ts --task "implement auth" --cwd /path/to/project
//   npx ts-node generate-agents-md.ts --task "implement auth" --model deepseek-v4-flash
//
// Output: writes AGENTS.md to stdout (pipe to file or temp workspace).

import { resolve } from '../../enrich/resolver';
import type { EnrichInput, ResolvedContext } from '../../enrich/contract';

interface GenerateOptions {
  task: string;
  cwd: string;
  model?: string;
  isaPath?: string;
  maxTurns?: number;
}

function parseArgs(): GenerateOptions {
  const args = process.argv.slice(2);
  const opts: GenerateOptions = { task: '', cwd: process.cwd() };
  
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    const next = args[i + 1];
    
    if (arg === '--task' && next) { opts.task = next; i++; }
    else if (arg === '--cwd' && next) { opts.cwd = next; i++; }
    else if (arg === '--model' && next) { opts.model = next; i++; }
    else if (arg === '--isa-path' && next) { opts.isaPath = next; i++; }
    else if (arg === '--max-turns' && next) { opts.maxTurns = parseInt(next, 10); i++; }
  }
  
  return opts;
}

function extractIntent(task: string): { objective: string; notWants: string } {
  const normalized = task.replace(/\s+/g, ' ').trim();
  
  // Extract not-wants from negative cues
  const notPatterns = [
    /\b(?:do(?:es)?n['']?t|do(?:es)? not)\s+(.+)/i,
    /\bavoid\s+(.+)/i,
    /\bwithout\s+(.+)/i,
  ];
  
  let notWants = 'none';
  for (const re of notPatterns) {
    const m = normalized.match(re);
    if (m && m[1]) {
      notWants = m[1].replace(/[.,;:!?]+$/, '').trim();
      break;
    }
  }
  
  // Objective: first clause
  const firstClause = normalized.match(/^[^.!?;\n]+/);
  const objective = firstClause ? firstClause[0].trim() : normalized;
  
  return { objective, notWants };
}

function formatGuardrails(isa: ResolvedContext['isa']): string {
  if (!isa) return 'No ISA context available.';
  
  const parts: string[] = [];
  
  if (isa.principles?.trim()) {
    parts.push(`**Principles:**\n${isa.principles.split('\n').slice(0, 3).join('\n')}`);
  }
  if (isa.constraints?.trim()) {
    parts.push(`**Constraints:**\n${isa.constraints.split('\n').slice(0, 3).join('\n')}`);
  }
  if (isa.outOfScope?.trim()) {
    parts.push(`**Out of Scope:**\n${isa.outOfScope.split('\n').slice(0, 3).join('\n')}`);
  }
  if (isa.antiCriteria?.trim()) {
    parts.push(`**Anti-Criteria (do NOT do these):**\n${isa.antiCriteria}`);
  }
  
  return parts.length > 0 ? parts.join('\n\n') : 'No guardrails defined.';
}

function formatMemory(memory: ResolvedContext['memory']): string {
  const lines: string[] = [];
  
  if (memory.worked) {
    lines.push(`- Recent success patterns: ${memory.worked}`);
  }
  if (memory.failed) {
    lines.push(`- Recent failure patterns: ${memory.failed}`);
  }
  if (memory.open) {
    lines.push(`- Open work context: ${memory.open}`);
  }
  
  return lines.length > 0 ? lines.join('\n') : 'No memory pointers available.';
}

function generateAgentsMd(opts: GenerateOptions, ctx: ResolvedContext): string {
  const { objective, notWants } = extractIntent(opts.task);
  const guardrails = formatGuardrails(ctx.isa);
  const memory = formatMemory(ctx.memory);
  
  const modelHint = opts.model ? `\nRecommended model: \`${opts.model}\`` : '';
  const maxTurnsHint = opts.maxTurns ? `\nMax turns: ${opts.maxTurns}` : '';
  
  return `# Temperance Engine - Task Context

<!-- Generated by SP0 enrichment for Command Code dispatch -->

## Task

**Objective:** ${objective}
**Avoid:** ${notWants}${modelHint}${maxTurnsHint}

## Enrichment Context

### Guardrails (from ISA)

${guardrails}

### Memory Pointers

${memory}

${ctx.isaPath ? `### ISA Reference\n\nActive ISA: \`${ctx.isaPath}\`` : ''}

## Operating Instructions

1. **Focus on the objective** - Complete the task described above
2. **Respect guardrails** - Do not violate the constraints or anti-criteria
3. **Leverage memory** - If past failures are referenced, avoid those patterns
4. **Stay in scope** - Do not expand beyond the stated objective
5. **Verify before claiming done** - Run tests, check compilation, confirm behavior

## Response Format

When complete, provide:
1. Summary of what was done (2-3 sentences)
2. Files changed (list)
3. Verification performed (tests run, manual checks)
4. Any blockers or follow-ups needed

---

*Temperance Engine SP0 enrichment layer*
*ISA-driven context for multi-model dispatch*
`;
}

async function main() {
  const opts = parseArgs();
  
  if (!opts.task) {
    console.error('Usage: generate-agents-md.ts --task "..." [--cwd path] [--model name]');
    process.exit(1);
  }
  
  const input: EnrichInput = {
    prompt: opts.task,
    cwd: opts.cwd,
    surface: 'opencode', // Command Code treated as opencode-family surface
  };
  
  try {
    const ctx = await resolve(input);
    
    // Override isaPath if explicitly provided
    if (opts.isaPath) {
      ctx.isaPath = opts.isaPath;
    }
    
    const agentsMd = generateAgentsMd(opts, ctx);
    console.log(agentsMd);
  } catch (err) {
    console.error('Error generating AGENTS.md:', err);
    process.exit(1);
  }
}

main();
