#!/usr/bin/env bash
# package/adapters/command-code/generate-agents-md.sh
# Generates a Command Code-compatible AGENTS.md with SP0 enrichment context embedded.
# Preserves the existing Bash ISA/memory renderer and delegates only the
# pointer catalog to the canonical Bun resolver/serializer.
#
# Usage:
#   ./generate-agents-md.sh --task "implement auth" --cwd /path/to/project
#   ./generate-agents-md.sh --task "implement auth" --model deepseek-v4-flash
#
# Output: buffers and validates the complete document, then writes it to stdout.
# This file never promotes a project file; the dispatcher owns its private
# same-directory AGENTS.md.tmp -> AGENTS.md rename.

set -euo pipefail
umask 077

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTEXT_SOURCES_HELPER="$SCRIPT_DIR/context-sources-line.ts"
AGENTS_VALIDATOR="$SCRIPT_DIR/validate-agents-md.ts"
BUN_BIN="$(command -v bun || true)"

# Defaults
TASK=""
CWD="$(pwd)"
MODEL=""
MAX_TURNS=""
ISA_PATH=""
CONTEXT_SOURCES_LINE=""
AGENTS_OUTPUT=""

cleanup() {
  if [[ -n "${AGENTS_OUTPUT:-}" ]]; then
    rm -f "$AGENTS_OUTPUT"
  fi
}
trap cleanup EXIT INT TERM HUP

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --task) TASK="$2"; shift 2 ;;
    --cwd) CWD="$2"; shift 2 ;;
    --model) MODEL="$2"; shift 2 ;;
    --max-turns) MAX_TURNS="$2"; shift 2 ;;
    --isa-path) ISA_PATH="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [[ -z "$TASK" ]]; then
  echo "Usage: $0 --task '...' [--cwd path] [--model name]" >&2
  exit 1
fi

# Resolve ISA path
resolve_isa_path() {
  local cwd="$1"
  
  # (1) Local ISA.md
  if [[ -f "$cwd/ISA.md" ]]; then
    echo "$cwd/ISA.md"
    return
  fi
  
  # (2) Newest WORK dir with ISA.md or PRD.md
  local work_root="$HOME/.claude/MEMORY/WORK"
  if [[ -d "$work_root" ]]; then
    for dir in $(ls -t "$work_root" 2>/dev/null | head -5); do
      local full="$work_root/$dir"
      if [[ -f "$full/ISA.md" ]]; then
        echo "$full/ISA.md"
        return
      fi
      if [[ -f "$full/PRD.md" ]]; then
        echo "$full/PRD.md"
        return
      fi
    done
  fi
  
  echo ""
}

# Extract a section from markdown
slice_section() {
  local file="$1"
  local heading="$2"
  
  if [[ ! -f "$file" ]]; then
    echo ""
    return
  fi
  
  # Use awk to extract section content
  awk -v h="$heading" '
    BEGIN { IGNORECASE=1; in_section=0 }
    /^## / {
      if (in_section) exit
      if (tolower($0) ~ "^## *" tolower(h) " *$") in_section=1
      next
    }
    in_section { print }
  ' "$file" | head -10
}

# Extract intent from task
extract_intent() {
  local task="$1"
  
  # First clause (before . ! ? ;)
  echo "$task" | sed 's/[.!?;].*//' | head -c 100
}

# Extract not-wants from task
extract_not_wants() {
  local task="$1"
  
  # Look for "avoid", "don't", "without", etc.
  if echo "$task" | grep -qi "avoid"; then
    echo "$task" | sed -n 's/.*avoid \([^,.]*\).*/\1/ip' | head -1
  elif echo "$task" | grep -qi "don't\|do not"; then
    echo "$task" | sed -n "s/.*don't \([^,.]*\).*/\1/ip" | head -1
  elif echo "$task" | grep -qi "without"; then
    echo "$task" | sed -n 's/.*without \([^,.]*\).*/\1/ip' | head -1
  else
    echo "none"
  fi
}

# Find newest failure record
newest_failure() {
  local failures_root="$HOME/.claude/MEMORY/LEARNING/FAILURES"
  if [[ -d "$failures_root" ]]; then
    find "$failures_root" -type f -name "*.md" 2>/dev/null | head -1 || echo ""
  else
    echo ""
  fi
}

# Main generation
render() {
  local isa_path
  if [[ -n "$ISA_PATH" ]]; then
    isa_path="$ISA_PATH"
  else
    isa_path=$(resolve_isa_path "$CWD")
  fi
  
  local objective
  objective=$(extract_intent "$TASK")
  
  local not_wants
  not_wants=$(extract_not_wants "$TASK")
  
  local principles=""
  local constraints=""
  local out_of_scope=""
  local anti_criteria=""
  
  if [[ -n "$isa_path" && -f "$isa_path" ]]; then
    principles=$(slice_section "$isa_path" "Principles")
    constraints=$(slice_section "$isa_path" "Constraints")
    out_of_scope=$(slice_section "$isa_path" "Out of Scope")
    # Anti-criteria: lines containing "Anti:" in Criteria section
    anti_criteria=$(slice_section "$isa_path" "Criteria" | grep -i "anti:" || echo "")
  fi
  
  local failure_record
  failure_record=$(newest_failure)
  
  # Generate AGENTS.md
  cat <<EOF
# Temperance Engine - Task Context

<!-- Generated by SP0 enrichment for Command Code dispatch -->

## Task

**Objective:** $objective
**Avoid:** ${not_wants:-none}
EOF

  if [[ -n "$MODEL" ]]; then
    echo "**Recommended model:** \`$MODEL\`"
  fi
  if [[ -n "$MAX_TURNS" ]]; then
    echo "**Max turns:** $MAX_TURNS"
  fi

  cat <<EOF

## Enrichment Context

### Guardrails (from ISA)

EOF

  if [[ -n "$principles" ]]; then
    echo "**Principles:**"
    echo "$principles" | head -3
    echo ""
  fi
  
  if [[ -n "$constraints" ]]; then
    echo "**Constraints:**"
    echo "$constraints" | head -3
    echo ""
  fi
  
  if [[ -n "$out_of_scope" ]]; then
    echo "**Out of Scope:**"
    echo "$out_of_scope" | head -3
    echo ""
  fi
  
  if [[ -n "$anti_criteria" ]]; then
    echo "**Anti-Criteria (do NOT do these):**"
    echo "$anti_criteria"
    echo ""
  fi
  
  if [[ -z "$principles$constraints$out_of_scope$anti_criteria" ]]; then
    echo "No ISA context available."
    echo ""
  fi

  cat <<EOF
### Memory Pointers

EOF

  if [[ -n "$failure_record" ]]; then
    echo "- Recent failure patterns: \`$failure_record\`"
  fi
  
  if [[ -n "$isa_path" ]]; then
    local project_memory
    project_memory=$(dirname "$isa_path")/MEMORY.md
    if [[ -f "$project_memory" ]]; then
      echo "- Project memory: \`$project_memory\`"
    fi
  fi
  
  echo ""

  if [[ -n "$isa_path" ]]; then
    cat <<EOF
### ISA Reference

Active ISA: \`$isa_path\`

EOF
  fi

  cat <<EOF
### Context Source Pointers

$CONTEXT_SOURCES_LINE

EOF

  cat <<EOF
## Operating Instructions

1. **Focus on the objective** - Complete the task described above
2. **Respect guardrails** - Do not violate the constraints or anti-criteria
3. **Leverage memory** - If past failures are referenced, avoid those patterns
4. **Stay in scope** - Do not expand beyond the stated objective
5. **Verify before claiming done** - Run tests, check compilation, confirm behavior

## Response Format

When complete, provide:
1. Summary of what was done (2-3 sentences)
2. Files changed (list)
3. Verification performed (tests run, manual checks)
4. Any blockers or follow-ups needed

---

*Temperance Engine SP0 enrichment layer*
*ISA-driven context for multi-model dispatch*
EOF
}

main() {
  if [[ -z "$BUN_BIN" || ! -x "$BUN_BIN" ]]; then
    echo "Command Code context-source projection requires Bun" >&2
    return 127
  fi
  if [[ ! -r "$CONTEXT_SOURCES_HELPER" || ! -r "$AGENTS_VALIDATOR" ]]; then
    echo "Command Code context-source adapter is incomplete" >&2
    return 127
  fi

  if ! CONTEXT_SOURCES_LINE=$("$BUN_BIN" "$CONTEXT_SOURCES_HELPER" --cwd "$CWD"); then
    echo "Command Code context-source projection failed" >&2
    return 1
  fi
  case "$CONTEXT_SOURCES_LINE" in
    context-sources:\ *) ;;
    *)
      echo "Command Code context-source projection returned an invalid line" >&2
      return 1
      ;;
  esac
  case "$CONTEXT_SOURCES_LINE" in
    *$'\n'*|*$'\r'*|*$'\342\200\250'*|*$'\342\200\251'*)
      echo "Command Code context-source projection returned multiple lines" >&2
      return 1
      ;;
  esac

  AGENTS_OUTPUT=$(mktemp "${TMPDIR:-/tmp}/temperance-command-code-agents.XXXXXX")
  render > "$AGENTS_OUTPUT"
  if ! "$BUN_BIN" "$AGENTS_VALIDATOR" --file "$AGENTS_OUTPUT"; then
    echo "Refusing invalid Command Code AGENTS.md" >&2
    return 1
  fi
  command cat "$AGENTS_OUTPUT"
}

main "$@"
