import {expect,test} from "bun:test";
import {selectTrivectorCandidate as select,TRIVECTOR_SELECTION_POLICY_DIGEST,TRIVECTOR_LEGACY_G9_POLICY} from "../src/routing/trivector-selection.ts";
import {TRIVECTOR_POLICY_DIGEST} from "../src/routing/trivector-contracts.ts";
const now=1791200000000,sha=`sha256:${"a".repeat(64)}`,iso=(n:number)=>new Date(n).toISOString();
const stamp=()=>({observed_at:iso(now-1000),expires_at:iso(now+10000),source_kind:"reviewed-observation",receipt_digest:sha,subject_fingerprint:sha});
function candidate(id="a",provider="provider",domain="domain"){return {id,provider,model:"vendor/model",scope:"configured-combo-member",subject_fingerprint:sha,static_rank:1,gates:{...stamp(),activation:"observed-enabled",operator_authorization:"observed-allowed",entitlement:"observed-available",catalog:"resolved",capability:"compatible",circuit:"closed"},fit:{...stamp(),score:.9},quota:[{...stamp(),id:"hour",unit:"requests",state:"known",remaining:100,inflight:0,margin:0,estimated_units:1,blocking:true,resets_at:iso(now+60000)}],operational_outcomes:{...stamp(),scope:"configured-combo-member",outcome_kind:"transport",successes:10,failures:0,consecutive_failures:0,rate_limit_events:[],latency_ms:100},failure_domain:{...stamp(),id:domain,provenance:"reviewed"},limitations:[]};}
function fixture(){return {schema:"temperance.trivector-evidence-packet.v1",observed_at:iso(now),policy:{version:"trivector-v4.1.0",digest:TRIVECTOR_POLICY_DIGEST,min_providers:1,min_failure_domains:1,observation_max_age_ms:300000},request:{id:"request",task_class:"coding",arbitration:"v4.1",pinned_candidate_id:null},candidates:[candidate()]};}
test("pure proposed head is frozen coarse context with all authority false",()=>{const p=fixture(),d=select(p,now);expect(d.proposed_head).toBe("a");expect(d.state).toBe("proposed");expect(d.head_scope).toBe("configured-combo-member");expect(d.candidates[0]!.flags).toContain("COARSE_SCOPE");for(const k of ["execution_authorized","capacity_authorization","lease_authorized","effect_authorized"] as const)expect(d[k]).toBe(false);expect(d.semantic_acceptance).toBeNull();expect(Object.isFrozen(d.candidates[0])).toBe(true);expect(d.policy_digest).toBe(TRIVECTOR_SELECTION_POLICY_DIGEST);});
test("binary gates fail before pins; explicit capability false gates but uncertainty does not",()=>{for(const patch of [{activation:"unknown"},{operator_authorization:"observed-denied"},{entitlement:"unknown"},{catalog:"unresolved"},{circuit:"open"},{capability:"resolved-incompatible"}]){const p=fixture();Object.assign(p.candidates[0]!.gates,patch);(p.request as any).pinned_candidate_id="a";expect(select(p,now).proposed_head).toBeNull();}for(const capability of ["context-conflict","tool-conflict","modality-conflict","structured-output-null","unknown"]){const p=fixture();p.candidates[0]!.gates.capability=capability;expect(select(p,now).proposed_head).toBe("a");expect(select(p,now).candidates[0]!.flags).toContain("CAPABILITY_UNCERTAIN");}});
test("stale future binary gates and stale fits hold",()=>{for(const mutate of [(p:any)=>p.candidates[0].gates.expires_at=iso(now-1),(p:any)=>{p.candidates[0].gates.observed_at=iso(now+1);p.candidates[0].gates.expires_at=iso(now+2);},(p:any)=>p.candidates[0].fit.expires_at=iso(now-1)]){const p=fixture();mutate(p);expect(select(p,now).proposed_head).toBeNull();}});
test("unknown stale reset-expired quota remains visible and omitted; known blocking exhaustion gates",()=>{for(const mutate of [(p:any)=>{p.candidates[0].quota[0].state="unknown";for(const k of ["remaining","margin","inflight","estimated_units"])p.candidates[0].quota[0][k]=null;},(p:any)=>p.candidates[0].quota[0].expires_at=iso(now-1),(p:any)=>p.candidates[0].quota[0].resets_at=iso(now-1),(p:any)=>p.candidates[0].quota=[]]){const p=fixture();mutate(p);const d=select(p,now);expect(d.proposed_head).toBe("a");expect(d.candidates[0]!.quota_headroom).toBeNull();expect(d.candidates[0]!.flags.some(f=>f.startsWith("QUOTA_"))).toBe(true);}const p=fixture();p.candidates[0]!.quota[0]!.remaining=0;expect(select(p,now).candidates[0]!.reasons).toContain("QUOTA_EXHAUSTED");p.candidates[0]!.quota[0]!.blocking=false;expect(select(p,now).proposed_head).toBe("a");});
test("fit bucket precedes pin and quota latency static ties",()=>{const p=fixture();p.candidates.push(candidate("b"));p.candidates[1]!.fit.score=.87;(p.request as any).pinned_candidate_id="b";expect(select(p,now).proposed_head).toBe("a");p.candidates[1]!.fit.score=.89;expect(select(p,now).arbiter).toBe("pin");expect(select(p,now).proposed_head).toBe("b");p.request.pinned_candidate_id=null;p.candidates[1]!.quota[0]!.remaining=50;expect(select(p,now).arbiter).toBe("quota_headroom");p.candidates[1]!.quota[0]!.remaining=100;p.candidates[1]!.operational_outcomes.latency_ms=50;expect(select(p,now).arbiter).toBe("latency");p.candidates[1]!.operational_outcomes.latency_ms=100;expect(select(p,now).proposed_head).toBe("a");});
test("legacy G9 exact thresholds differ from v41 without using 429 mass",()=>{expect(TRIVECTOR_LEGACY_G9_POLICY).toEqual({version:"trivector-legacy-g9.v1",sample_min:5,consecutive_failures_min:5});const p=fixture(),o=p.candidates[0]!.operational_outcomes;o.successes=0;o.failures=5;o.consecutive_failures=5;p.request.arbitration="legacy";expect(select(p,now).proposed_head).toBeNull();p.request.arbitration="v4.1";expect(select(p,now).proposed_head).toBe("a");o.failures=20;expect(select(p,now).proposed_head).toBeNull();o.failures=0;o.consecutive_failures=0;o.rate_limit_events=Array.from({length:32},(_,i)=>iso(now-1000-i));expect(select(p,now).candidates[0]!.operational_g9).toBe(false);expect(select(p,now).candidates[0]!.hazard).toBeGreaterThan(31);});
test("429 hazard affects v41 quota but stale outcome evidence never gates",()=>{const p=fixture();p.candidates.push(candidate("b"));p.candidates[0]!.operational_outcomes.rate_limit_events=[iso(now-1000)];expect(select(p,now).proposed_head).toBe("b");p.request.arbitration="legacy";expect(select(p,now).proposed_head).toBe("a");const o=p.candidates[0]!.operational_outcomes;o.successes=0;o.failures=20;o.consecutive_failures=20;o.expires_at=iso(now-1);expect(select(p,now).candidates[0]!.operational_g9).toBe(false);expect(select(p,now).candidates[0]!.flags).toContain("OUTCOMES_STALE");});
test("provider/domain floors are diagnostic hold; unknown provenance counts zero",()=>{const p=fixture();p.policy.min_providers=2;p.policy.min_failure_domains=2;expect(select(p,now).proposed_head).toBeNull();p.candidates.push(candidate("b","other","otherdomain"));expect(select(p,now).proposed_head).toBe("a");p.candidates[1]!.failure_domain.provenance="unknown";(p.candidates[1]!.failure_domain as any).id=null;expect(select(p,now).diversity.proven_failure_domains).toBe(1);expect(select(p,now).reasons).toContain("FAILURE_DOMAIN_FLOOR_UNMET");p.candidates=[];expect(select(p,now).reasons).toContain("NO_SURVIVORS");});
test("full normalized evidence policy and injected time bind deterministic digest",()=>{const p=fixture();p.candidates.push(candidate("b"));const q=structuredClone(p);q.candidates.reverse();expect(select(p,now)).toEqual(select(q,now));expect(select(p,now+1).consumed_evidence_digest).not.toBe(select(p,now).consumed_evidence_digest);q.candidates[0]!.gates.receipt_digest=`sha256:${"b".repeat(64)}`;expect(select(q,now).consumed_evidence_digest).not.toBe(select(p,now).consumed_evidence_digest);});
test("unsafe input rejects without reading getter or leaking raw fields",()=>{let traps=0;const p=fixture();Object.defineProperty(p,"private_path",{enumerable:true,get(){traps++;throw Error("/private/context");}});expect(()=>select(p,now)).toThrow("TRIVECTOR_PACKET_UNSAFE");expect(traps).toBe(0);});

test("matching active head or seat limitations remove pinned candidates; stale facts remain flags",()=>{
 for(const position of ["head","seat"]){const p=fixture();(p.request as any).pinned_candidate_id="a";(p.candidates[0]!.limitations as any).push({...stamp(),id:"limit",task_class:"coding",position,reason:"operational-failure"});expect(select(p,now).proposed_head).toBeNull();expect(select(p,now).candidates[0]!.reasons).toContain("LIMITATION_ACTIVE");const l=(p.candidates[0]!.limitations as any)[0];l.expires_at=iso(now-1);expect(select(p,now).proposed_head).toBe("a");expect(select(p,now).candidates[0]!.flags).toContain("LIMITATION_STALE");l.observed_at=iso(now+1);l.expires_at=iso(now+2);expect(select(p,now).candidates[0]!.flags).toContain("LIMITATION_FUTURE");l.observed_at=iso(now-1000);l.expires_at=iso(now+10000);l.task_class="writing";expect(select(p,now).proposed_head).toBe("a");}
});
test("legacy explicit fractions and v41 window headroom choose divergent heads",()=>{
 const p=fixture();p.candidates.push(candidate("b"));(p.candidates[0] as any).legacy_quota={...stamp(),remaining_fraction:.1};(p.candidates[1] as any).legacy_quota={...stamp(),remaining_fraction:.9};p.candidates[1]!.quota[0]!.remaining=10;
 expect(select(p,now).proposed_head).toBe("a");expect(select(p,now).candidates[0]!.quota_signal_kind).toBe("v41-window-headroom");p.request.arbitration="legacy";expect(select(p,now).proposed_head).toBe("b");expect(select(p,now).candidates[1]!.quota_headroom).toBe(.9);expect(select(p,now).candidates[1]!.quota_signal_kind).toBe("legacy-fraction");
 delete (p.candidates[1] as any).legacy_quota;delete (p.candidates[0] as any).legacy_quota;expect(select(p,now).proposed_head).toBe("a");for(const c of select(p,now).candidates){expect(c.quota_headroom).toBeNull();expect(c.flags).toContain("QUOTA_UNKNOWN");}
});
test("legacy fraction zero narrows without v41 window exhaustion gate; freshness remains visible",()=>{
 const p=fixture();p.request.arbitration="legacy";p.candidates[0]!.quota[0]!.remaining=0;(p.candidates[0] as any).legacy_quota={...stamp(),remaining_fraction:0};expect(select(p,now).proposed_head).toBe("a");expect(select(p,now).candidates[0]!.reasons).not.toContain("QUOTA_EXHAUSTED");
 const q=(p.candidates[0] as any).legacy_quota;q.expires_at=iso(now-1);expect(select(p,now).candidates[0]!.quota_headroom).toBeNull();expect(select(p,now).candidates[0]!.flags).toContain("QUOTA_STALE");q.observed_at=iso(now+1);q.expires_at=iso(now+2);expect(select(p,now).candidates[0]!.flags).toContain("QUOTA_FUTURE");p.request.arbitration="v4.1";expect(select(p,now).proposed_head).toBeNull();
});

test("quota flags describe active signal only",()=>{const p=fixture();p.request.arbitration="legacy";p.candidates[0]!.quota=[];(p.candidates[0] as any).legacy_quota={...stamp(),remaining_fraction:.8};expect(select(p,now).candidates[0]!.flags).not.toContain("QUOTA_UNKNOWN");expect(select(p,now).candidates[0]!.quota_headroom).toBe(.8);p.candidates[0]!.quota=[{...candidate().quota[0]!,expires_at:iso(now-1)}];expect(select(p,now).candidates[0]!.flags).not.toContain("QUOTA_STALE");p.request.arbitration="v4.1";(p.candidates[0] as any).legacy_quota.expires_at=iso(now-1);p.candidates[0]!.quota=[candidate().quota[0]!];expect(select(p,now).candidates[0]!.flags).not.toContain("QUOTA_STALE");});

test("half-open circuit proposal requires owner probe without lease authority",()=>{const p=fixture();p.candidates[0]!.gates.circuit="open";expect(select(p,now).proposed_head).toBeNull();p.candidates[0]!.gates.circuit="half-open";const d=select(p,now);expect(d.proposed_head).toBe("a");expect(d.candidates[0]!.flags).toContain("CIRCUIT_PROBE_REQUIRED");expect(d.lease_authorized).toBe(false);expect(d.execution_authorized).toBe(false);p.candidates[0]!.gates.circuit="unknown";expect(select(p,now).proposed_head).toBeNull();});
