/**
 * Task 1 — Migration schema re-exports and schema-level constants.
 *
 * This module is the canonical import point for Task 2 and Task 3 when
 * they need schema constants, the ValidationResult type, and the compiled
 * validator without importing the full contracts module directly.
 *
 * Exports are additive; nothing in the main schema.ts is modified.
 */
export {
  MIGRATION_SNAPSHOT_SCHEMA,
  MIGRATION_TARGET_SCHEMA,
  SUPPORTED_SNAPSHOT_MAJOR,
  SUPPORTED_TARGET_MAJOR,
  MAX_MIGRATION_SNAPSHOT_BYTES,
  OPERATING_ORGAN_IDS,
  COGNITIVE_ORGAN_IDS,
  WILL_ROLE_DESKS,
  CAPABILITY_HIT_MODE_IDS,
  CAPABILITY_HIT_SOURCE_REF,
  ADYTUM_OWNER_TOPIC_COUNT,
  ADYTUM_CONSUMER_TOPIC_COUNT,
  validateMigrationSnapshot,
  validateMigrationTarget,
  makeMigrationFinding,
  computeWorkBindingDigest,
  assessMigrationCompatibility,
  type ValidationResult,
  type MigrationSnapshotV1,
  type MigrationTargetV1,
  type MigrationFindingV1,
  type OrganEvidenceRef,
  type InputDependencyRef,
  type KnowledgeRef,
  type CanonicalKnowledgeRef,
  type DerivedKnowledgeRef,
  type WorkObjectRef,
  type CellEffectClass,
  type CellEffectKind,
  type EvidenceDimensions,
  type WillRoleDeskAssignment,
  type WillRoleDesk,
  type ExternalProductRef,
  type CompatibilityObservations,
  type ToolchainRequirement,
  type FreshnessState,
  type IndependentVerdict,
  type AdmissionState,
  type RuntimeState,
  type VerificationState,
  type OperatingOrganId,
  type CognitiveOrganId,
  type OrganId,
  type MakeFindingOptions,
  type CapabilityHitModeId,
  type CapabilityHitModeRef,
  type CapabilityHitModesDeclaration,
  type CellEffectOutcome,
} from "./contracts.ts";
export type {
  VerdictAttestation,
  ArtifactLineage,
  ArtifactStage,
  AdytumParityEvidence,
  AdytumTopicRef,
  ExpectedWorkBinding,
  ExpectedVerdictAnchor,
  ExpectedStageAnchor,
  ExpectedAdytumContext,
  ExpectedTopicTuple,
  MigrationExpectedContext,
  CompatibilityStatus,
  CompatibilityAssessment,
} from "./contracts.ts";
